### ISSUE TITLE
Very slow script startup

### ISSUE THREAD

**Issue by maBarabas** [lvgl/lv_img_conv#11]
I've installed this script from the [npm registry](https://www.npmjs.com/package/lv_img_conv).

When I run it from the command line, the startup takes a few seconds. This is the same every time it is started.

I'm trying to convert about a dozen images, so this really slows down the build. Is there any way to speed it up? The old PHP script was quite fast, but is more difficult to run on windows, so I'm looking into this nodejs version.

```
$ time lv_img_conv --version
0.1.3

real    0m2.837s
user    0m4.670s
sys     0m0.210s
```

**Comment by embeddedt** [comment]
FYI, it's possible to pass multiple images at once (although this isn't documented). The output file will have the same name and path but with the image extension replaced by `.c`.

**Comment by maBarabas** [comment]
I'm using the `-o` option to place the generated files in `CMAKE_CURRENT_BINARY_DIR`. It doesn't look like this supports multiple input files, is this correct?

**Comment by embeddedt** [comment]
In 0.2.1 you can change the working directory to affect the output path (as you suggested).

**Comment by maBarabas** [comment]
Thanks, I've decided to stay with PHP for now, `php.exe` works the same as `php` on Linux. The [php docs](https://www.php.net/manual/en/install.windows.commandline.php) made it more confusing than it really is.

**Comment by embeddedt** [comment]
FYI, startup should be a lot faster now. I've done some refactoring in the latest version and upgraded `ts-node` which sped things up a lot.
