### ISSUE TITLE
Place converted images in current working directory

### ISSUE THREAD

**Issue by maBarabas** [lvgl/lv_img_conv#12]
The php script places the generated files in the current working directory. This allows a lot more flexibility in where the files are places. E.G. in CMake we can place the generated files in the build folder:

```
    add_custom_command(OUTPUT ${C}
        COMMAND php ${CMAKE_CURRENT_LIST_DIR}/img_conv_core.php name=${T}&img=${P}
        DEPENDS ${P}
        WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
        VERBATIM)
```

This is not possible with this script. Could you add an option to place the outputs in the working directory instead of next to the input files?

**Comment by embeddedt** [comment]
I've made it the default rather than adding an option, as it just makes more sense to do it this way.
