### ISSUE TITLE
Off-By-One Size Error When Converting Images To Alpha-Only C code

### ISSUE THREAD

**Issue by alekleme** [lvgl/lv_img_conv#16]
# What happens?
When I use `lv_img_conv.js` to export an image to a C array with the format `CF_ALPHA_4_BIT` the resulting C file specifies a `data_size` that is one larger than I expect.

# Replication
1. Create an image ([I've attached a sample](https://user-images.githubusercontent.com/86499390/157925606-b07207e7-53b8-4f23-bb15-df14e118d79c.png)).
2. Convert using `./lv_img_conv.js <image> -f -c CF_ALPHA_4_BIT`.
3. Compare `.data_size` to `WIDTH * HEIGHT * 4 / 8`.

(With the 32x32 sample image, I expect `32*32*4/8 = 512` but I get 513)
```c
const lv_img_dsc_t test_image = {
  .header.cf = LV_IMG_CF_ALPHA_4BIT,
  .header.always_zero = 0,
  .header.reserved = 0,
  .header.w = 32,
  .header.h = 32,
  .data_size = 513,
  .data = test_image_map,
};
```
Note that the C array output only has 512 bytes in it, so if the LVGL library reads 513 bytes, it'll read into uninitialized memory and not padding.

# Investigation
I think that the cause is likely this line: https://github.com/lvgl/lv_img_conv/blob/master/lib/convert.ts#L575 Removing it resolves the issue - but I do not know the full effects or why the line is there.

**Comment by embeddedt** [comment]
Hi, sorry for the delay. I have done some refactoring/testing and I believe this is fixed now. Please test it again with [this link](https://lvgl.github.io/lv_img_conv/).

@kisvegabor Can you update the converter when you have a chance?

**Comment by alekleme** [comment]
That link seems to no longer have the off-by-one bug. Nice!
I just tested it on the same image and settings listed in the report.

**Comment by kisvegabor** [comment]
The online converter is updated.

**Comment by embeddedt** [comment]
Looks like it works well now, thanks!
