### ISSUE TITLE
Online Image Converter with gif not work

### ISSUE THREAD

**Issue by acer1204** [lvgl/lv_img_conv#18]
in LVGL 8.2.
when i use example libs gif folder, it wroking.
it's .header.cf = LV_IMG_CF_RAW.
buf if i use "LVGL Online Image Converter" to create raw .c.
it will not show anything. it show the header.cf is LV_IMG_CF_RAW_CHROMA,.
and lvgl 8.2 identifier "LV_IMG_CF_RAW_CHROMA" is undefined.
how to fix it?

**Comment by embeddedt** [comment]
Thanks for the report, I've fixed it here: https://github.com/lvgl/lv_img_conv/commit/2f7efaddb9b1307fa7e7b27d34752a7e32a63009

@kisvegabor I believe the converter on lvgl.io will need another update.

**Comment by embeddedt** [comment]
Thank you!

**Comment by right4mat** [comment]
i think this issue is back for lvgl.io
