### ISSUE TITLE
Multiple byte characters filename support

### ISSUE THREAD

**Issue by fralonra** [lvgl/lv_img_conv#24]
According to https://github.com/Automattic/node-canvas/issues/1802

> node-canvas doesn't handle multi-byte characters in filenames properly.

This means that the image path could not contain any Chinese/Japanese/Korean characters.
(But only failed on Windows. Related: https://github.com/tnfe/FFCreator/issues/3)

I'm wondering It there workaround without modifying the image path?

**Comment by embeddedt** [comment]
I would rather just add a note to the README advising that you need to rename these files before passing them to the converter. I suspect this is not the only tool with the issue.
