### ISSUE TITLE
Image Converter doesn't work with Firefox

### ISSUE THREAD

**Issue by 0x0203** [lvgl/lv_img_conv#27]
When converting an image using the online image converter (https://lvgl.io/tools/imageconverter) in Firefox, the resulting lvgl images are almost entirely garbage data. I'm using the latest version of firefox available on my distro (FF 105.0.1). I've attached a test image and the image converter output from both firefox and google chrome. I'm using format CF_TRUE_COLOR_ALPHA, with otherwise default options.

Test image - 4x4 pixels, with top left 4 pixels full red, top right 4 full green, bottom left 4 full blue, bottom right black/white checkered, saved as .png:
![img_test_png](https://user-images.githubusercontent.com/44345347/197292015-2fb33101-96d7-4897-9176-40333b17043a.png)

Converter output from Firefox (pixel data only):

`const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST LV_ATTRIBUTE_IMG_IMG_TEST_PNG uint8_t img_test_png_map[] = {`

`#if LV_COLOR_DEPTH == 1 || LV_COLOR_DEPTH == 8`
  `/*Pixel format: Alpha 8 bit, Red: 3 bit, Green: 3 bit, Blue: 2 bit*/`
  `0x2f, 0x86, 0x59, 0x1b, 0xcf, 0x25, 0xeb, 0xc6, `
  `0xd4, 0x38, 0x9f, 0xc0, 0xc7, 0x70, 0x62, 0x87, `
  `0x2f, 0x86, 0x59, 0x1b, 0xcf, 0x25, 0xeb, 0xc6, `
  `0xd4, 0x38, 0x9f, 0xc0, 0xc7, 0x70, 0x62, 0x87, `
`#endif`
`#if LV_COLOR_DEPTH == 16 && LV_COLOR_16_SWAP == 0`
  `/*Pixel format: Alpha 8 bit, Red: 5 bit, Green: 6 bit, Blue: 5 bit*/`
  `0x3d, 0x2b, 0x86, 0x28, 0x36, 0x1b, 0x5b, 0xcb, 0x25, 0x5d, 0xf2, 0xc6, `
  `0xe3, 0xcc, 0x38, 0xb8, 0x86, 0xc0, 0xd7, 0xb8, 0x70, 0x51, 0x60, 0x87, `
  `0x3d, 0x2b, 0x86, 0x28, 0x36, 0x1b, 0x5b, 0xcb, 0x25, 0x5d, 0xf2, 0xc6, `
  `0xe3, 0xcc, 0x38, 0xb8, 0x86, 0xc0, 0xd7, 0xb8, 0x70, 0x51, 0x60, 0x87, `
`#endif`
`#if LV_COLOR_DEPTH == 16 && LV_COLOR_16_SWAP != 0`
  `/*Pixel format: Alpha 8 bit, Red: 5 bit, Green: 6 bit, Blue: 5 bit  BUT the 2  color bytes are swapped*/`
  `0x2b, 0x3d, 0x86, 0x36, 0x28, 0x1b, 0xcb, 0x5b, 0x25, 0xf2, 0x5d, 0xc6, `
  `0xcc, 0xe3, 0x38, 0x86, 0xb8, 0xc0, 0xb8, 0xd7, 0x70, 0x60, 0x51, 0x87, `
  `0x2b, 0x3d, 0x86, 0x36, 0x28, 0x1b, 0xcb, 0x5b, 0x25, 0xf2, 0x5d, 0xc6, `
  `0xcc, 0xe3, 0x38, 0x86, 0xb8, 0xc0, 0xb8, 0xd7, 0x70, 0x60, 0x51, 0x87, `
`#endif`
`#if LV_COLOR_DEPTH == 32`
  `0xe9, 0x65, 0x27, 0x86, 0x41, 0xc2, 0x31, 0x1b, 0xda, 0x67, 0xc5, 0x25, 0xe5, 0x46, 0xef, 0xc6,` 
  `0x14, 0x9d, 0xc9, 0x38, 0xc3, 0xd3, 0x7d, 0xc0, 0xb7, 0x19, 0xb6, 0x70, 0x84, 0x07, 0x62, 0x87,` 
  `0xe9, 0x65, 0x27, 0x86, 0x41, 0xc2, 0x31, 0x1b, 0xda, 0x67, 0xc5, 0x25, 0xe5, 0x46, 0xef, 0xc6,` 
 ` 0x14, 0x9d, 0xc9, 0x38, 0xc3, 0xd3, 0x7d, 0xc0, 0xb7, 0x19, 0xb6, 0x70, 0x84, 0x07, 0x62, 0x87,`
`#endif`
`};`

Output from Google Chrome:

`const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST LV_ATTRIBUTE_IMG_IMG_TEST_PNG uint8_t img_test_png_map[] = {`
`#if LV_COLOR_DEPTH == 1 || LV_COLOR_DEPTH == 8`
`  /*Pixel format: Alpha 8 bit, Red: 3 bit, Green: 3 bit, Blue: 2 bit*/`
`  0xe0, 0xff, 0xe0, 0xff, 0x1c, 0xff, 0x1c, 0xff, `
`  0xe0, 0xff, 0xe0, 0xff, 0x1c, 0xff, 0x1c, 0xff, `
`  0x03, 0xff, 0x03, 0xff, 0x00, 0xff, 0xff, 0xff, `
`  0x03, 0xff, 0x03, 0xff, 0xff, 0xff, 0x00, 0xff, `
`#endif`
`#if LV_COLOR_DEPTH == 16 && LV_COLOR_16_SWAP == 0`
`  /*Pixel format: Alpha 8 bit, Red: 5 bit, Green: 6 bit, Blue: 5 bit*/`
`  0x00, 0xf8, 0xff, 0x00, 0xf8, 0xff, 0xe0, 0x07, 0xff, 0xe0, 0x07, 0xff, `
`  0x00, 0xf8, 0xff, 0x00, 0xf8, 0xff, 0xe0, 0x07, 0xff, 0xe0, 0x07, 0xff, `
`  0x1f, 0x00, 0xff, 0x1f, 0x00, 0xff, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff, `
`  0x1f, 0x00, 0xff, 0x1f, 0x00, 0xff, 0xff, 0xff, 0xff, 0x00, 0x00, 0xff, `
`#endif`
`#if LV_COLOR_DEPTH == 16 && LV_COLOR_16_SWAP != 0`
`  /*Pixel format: Alpha 8 bit, Red: 5 bit, Green: 6 bit, Blue: 5 bit  BUT the 2  color bytes are swapped*/`
`  0xf8, 0x00, 0xff, 0xf8, 0x00, 0xff, 0x07, 0xe0, 0xff, 0x07, 0xe0, 0xff, `
`  0xf8, 0x00, 0xff, 0xf8, 0x00, 0xff, 0x07, 0xe0, 0xff, 0x07, 0xe0, 0xff, `
`  0x00, 0x1f, 0xff, 0x00, 0x1f, 0xff, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff, `
`  0x00, 0x1f, 0xff, 0x00, 0x1f, 0xff, 0xff, 0xff, 0xff, 0x00, 0x00, 0xff, `
`#endif`
`#if LV_COLOR_DEPTH == 32`
`  0x00, 0x00, 0xff, 0xff, 0x00, 0x00, 0xff, 0xff, 0x00, 0xff, 0x00, 0xff, 0x00, 0xff, 0x00, 0xff, `
`  0x00, 0x00, 0xff, 0xff, 0x00, 0x00, 0xff, 0xff, 0x00, 0xff, 0x00, 0xff, 0x00, 0xff, 0x00, 0xff, `
`  0xff, 0x00, 0x00, 0xff, 0xff, 0x00, 0x00, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff, 0xff, `
`  0xff, 0x00, 0x00, 0xff, 0xff, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff, 0xff, 0x00, 0x00, 0x00, 0xff, `
`#endif`
`};`

**Comment by embeddedt** [comment]
Sorry for the very long delay in getting back to this issue.

I have just checked on FF 106.0.5 on Linux, and it seems to yield identical output to what you shared from Chrome (i.e. it works fine). Is it possible for you to try in a fresh Firefox profile without any other extensions/customizations?

**Comment by 0x0203** [comment]
No worries on the delay; not a pressing issue. Thanks for looking into it. 

Interesting... The only thing that fixed it for me in firefox was using a new profile. Getting rid of all addons didn't help, but for some reason a new profile does. I'm not sure what else a new profile changes that the converter relies on, or more specifically, what I've changed in mine, but if you want to close this bug, that's fine with me. If I need to, I can go through and figure out what change triggers the failure. 

Side note: with my profile and using the exact same input, the image converter is coming back with different data every time. Weird.

**Comment by embeddedt** [comment]
If you have a chance to figure out what is problematic about the old profile it would be great. If not, that's okay too. As an educated guess, perhaps check which entries in `about:config` are different?

I will close this for now but I'm happy to look into fixing it in the future.
