### ISSUE TITLE
alpha-only and indexed-color format binary file not working

### ISSUE THREAD

**Issue by XuNeo** [lvgl/lv_img_conv#9]
Hi,
Using the online [image converters](https://lvgl.io/tools/imageconverter), both alpha-only and indexed color format of binary are not working.
The generated binary file size is same as the one using true-color-alpha format.
 
Output format is always set to binary-rgb888 when tesing.

Check the binary data with c-array, it seems binary file always use 4byte/pixel

Attached is the original file and generated binary files.

Regards,
[binary-images.zip](https://github.com/lvgl/lv_img_conv/files/7524472/binary-images.zip)

**Comment by embeddedt** [comment]
Thanks for the report. This will be fixed when the online converter on lvgl.io is updated. In the meantime you can use the GitHub version: https://lvgl.github.io/lv_img_conv/

@kisvegabor Could you please deploy the latest version on lvgl.io?

**Comment by kisvegabor** [comment]
> Could you please deploy the latest version on lvgl.io?

Done!
